config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "homes#top"

  resources :books, only: [:create, :index, :show, :edit, :update, :destroy] do
    resource :favorites, only: [:create, :destroy]
    resources :book_comments, only: [:create, :destroy]
  end

  resources :users, only: [:index, :create, :show, :edit, :update] do
    resource :relationships, only: [:create, :destroy]
    get "search" => "users#search"
    member do
      get :following, :followers
    end
  end

  get "search" => "searches#search"
  get "home/about"=> "homes#about", as: "about"

  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#guest_sign_in'
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :books, dependent: :destroy
  has_many :active_relationships, class_name: "Relationship",
                                  foreign_key: "follower_id",
                                  dependent: :destroy
  has_many :passive_relationships, class_name: "Relationship",
                                   foreign_key: "followed_id",
                                     dependent: :destroy
  has_many :following, through: :active_relationships, source: :followed
  has_many :followers, through: :passive_relationships, source: :follower
  has_many :favorites, dependent: :destroy
  has_many :book_comments, dependent: :destroy

  has_many :user_rooms
  has_many :chats
  has_many :rooms, through: :user_rooms

  has_many :view_counts, dependent: :destroy

  has_one_attached :profile_image

  validates :name, uniqueness: true, length: { minimum: 2, maximum: 20 }
  validates :introduction, length: { maximum: 50 }

  def get_profile_image(width, height)
    unless profile_image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    profile_image.variant(resize_to_limit: [width, height]).processed
  end

  def follow(other_user)
    active_relationships.create(followed_id: other_user)
  end

  def unfollow(other_user)
    active_relationships.find_by(followed_id: other_user).destroy
  end

  def following?(other_user)
    following.include?(other_user)
  end

  def mutual_following?(current_user, user)
    current_user.following?(user) && user.following?(current_user)
  end

  def self.looks(search, word)
    if search == "perfect_match"
      @user = User.where("name LIKE?", "#{word}")
    elsif search == "forward_match"
      @user = User.where("name LIKE?","#{word}%")
    elsif search == "backward_match"
      @user = User.where("name LIKE?","%#{word}")
    elsif search == "partial_match"
      @user = User.where("name LIKE?","%#{word}%")
    else
      @user = User.all
    end
  end

  def self.guest
    find_or_create_by!(name: 'guestuser' ,email: 'guest@example.com') do |user|
      user.password = SecureRandom.urlsafe_base64
      user.name = "guestuser"
    end
  end

end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
  def guest_sign_in
    user = User.guest
    sign_in user
    redirect_to user_path(user), notice: 'guestuserでログインしました。'
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :ensure_guest_user, only: [:edit]
  def index
    @users = User.all
    @user = current_user
    @book = Book.new
  end

  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    @book.save
    redirect_to book_path(@book.id)
  end

  def show
    @user = User.find(params[:id])
    @books = @user.books
    @book = Book.new

    @today = @books.created_today
    @yesterday = @books.created_yesterday

    @this_week = @books.created_this_week
    @last_week = @books.created_last_week
  end

  def edit
    @user = User.find(params[:id])
    if @user == current_user
      render "edit"
    else
      redirect_to user_path(current_user)
    end
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to user_path(@user), notice: "You have updated user successfully."
    else
      render action: :edit
    end
  end

  def following
    user = User.find(params[:id])
    @users = user.following
    render "follows"
  end

  def followers
    user = User.find(params[:id])
    @users = user.followers
    render "followers"
  end

  def search
    @user = User.find(params[:user_id])
    @books = @user.books
    if params[:created_at] == ""
      @search_book = "日付を選択してください"
    else
      create_at = params[:created_at]
      @search_book = @books.where(['created_at LIKE ? ', "#{create_at}%"]).count
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :profile_image, :introduction)
  end

  def book_params
    params.require(:book).permit(:title, :body)
  end

  def ensure_guest_user
    @user = User.find(params[:id])
    if @user.name == "guestuser"
      redirect_to user_path(current_user) , notice: 'ゲストユーザーはプロフィール編集画面へ遷移できません。'
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_info.html.erb
<h2>User info</h2>
<%= image_tag user.get_profile_image(100,100) %>
<table class="table">
  <tbody>
    <tr></tr>
    <tr>
      <th>name</th>
      <th><%= user.name %></th>
    </tr>
    <tr>
      <th>introduction</th>
      <th><%= user.introduction %></th>
    </tr>
     <tr>
      <th>follows</th>
      <th>
        <%= link_to following_user_path(user.id) do %>
          <%= user.following.count %>
        <% end %>
      </th>
    </tr>
    <tr>
      <th>followers</th>
      <th>
        <%= link_to followers_user_path(user.id) do %>
          <%= user.followers.count %>
        <% end %>
      </th>
    </tr>
  </tbody>
</table>
<div class="row" id="follow_buttons_<%= user.id %>">
  <%= render "relationships/relationship", user: user %>
</div>
<% if (user = current_user) && (user.name != "guestuser")  %>
  <div class="row">
      <%= link_to edit_user_path(user), class: 'btn btn-outline-secondary btn-block' do %>
        <i class="fas fa-user-cog"></i>
      <% end %>
  </div>
<% end %>

app/views/users/_list.html.erb
<h2>User info</h2>
<%= image_tag user.get_profile_image(100,100) %>
<table class="table">
  <tbody>
    <tr></tr>
    <tr>
      <th>name</th>
      <th><%= user.name %></th>
    </tr>
    <tr>
      <th>introduction</th>
      <th><%= user.introduction %></th>
    </tr>
     <tr>
      <th>follows</th>
      <th>
        <%= link_to following_user_path(user.id) do %>
          <%= user.following.count %>
        <% end %>
      </th>
    </tr>
     <tr>
      <th>followers</th>
      <th>
          <%= link_to followers_user_path(user.id) do %>
              <%= user.followers.count %>
          <% end %>
      </th>
    </tr>
  </tbody>
</table>
<div class="row">
    <% if current_user != user %>
        <% if current_user.following?(user) %>
            <%= link_to 'フォロー外す', user_relationship_path(user.id), method: :delete, class: 'btn btn-primary' %>
        <% else %>
            <%= link_to 'フォローする', user_relationships_path(user.id), method: :post, class: 'btn btn-success' %>
        <% end %>
    <% end %>
</div>
<% if user == current_user %>
    <div class="row">
        <%= link_to edit_user_path(user), class: 'btn btn-outline-secondary btn-block' do %>
          <i class="fas fa-user-cog"></i>
        <% end %>
    </div>
<% end %>

app/views/users/_search.html.erb
<h2>検索結果</h2>
<table class='table table-bordered'>
  <thead>
    <tr>
      <th>投稿数</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td><%= search_book %></td>
    </tr>
  </tbody>
</table>

app/views/users/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
      <h2>User info</h2>

      <% if @user.errors.any? %>
        <div id="error_explanation">
          <h2> <%= @user.errors.count %>errors prohibited this obj from being saved:</h2>
          <ul>
            <% @user.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
          </ul>
        </div>
      <% end %>

      <%= form_with model: @user do |f| %>
        <div class="form-group">
          <label for="user_name">Name</label>
          <%= f.text_field :name, autofocus: true, id:"inputName", placeholder:current_user.name, class: 'form-control' %>
        </div>
        <div class="form-group">
          <label for="user_image">Image</label>
          <%= f.file_field :profile_image, placeholder: "プロフィール画像", accept: "image/*", class: 'form-control-file' %>
        </div>
        <div class="form-group">
          <label for="user_introduction">Introduction</label>
          <%= f.text_area :introduction, id:"inputIntroduction", class: 'form-control' %>
        </div>
        <div class="form-group">
          <%= f.submit "Update User", class: 'btn btn-secondary' %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/users/followers.html.erb
<h2>Followers</h2>
<% if @users.exists? %>
  <% @users.each do |user| %>
    <table class="table">
      <thead>
        <tr>
          <th>image</th>
          <th>name</th>
          <th colspan="4"></th>
        </tr>
      </thead>
      <tbody>
        <td><%= image_tag user.get_profile_image(80, 80) %></td>
        <td><%= user.name %></td>
        <td>フォロー数: <%= user.following.count %></td>
        <td>フォロワー数: <%= user.followers.count %></td>
        <td>
          <div class="row" id="follow_buttons_<%= user.id %>">
            <%= render "relationships/relationship", user: user %>
          </div>
        </td>
        <td><%= link_to 'Show', user_path(user) %></td>
      </tbody>
    </table>
  <% end %>
<% else %>
  <p>ユーザーはいません</p>
<% end %>

app/views/users/follows.html.erb
<h2>Following Users</h2>
<% if @users.exists? %>
  <% @users.each do |user| %>
    <table class="table">
      <thead>
        <tr>
          <th>image</th>
          <th>name</th>
          <th colspan="4"></th>
        </tr>
      </thead>
      <tbody>
        <td><%= image_tag user.get_profile_image(80, 80) %></td>
        <td><%= user.name %></td>
        <td>フォロー数: <%= user.following.count %></td>
        <td>フォロワー数: <%= user.followers.count %></td>
        <td>
          <div class="row" id="follow_buttons_<%= user.id %>">
            <%= render "relationships/relationship", user: user %>
          </div>
        </td>
        <td><%= link_to 'Show', user_path(user) %></td>
      </tbody>
    </table>
  <% end %>
<% else %>
  <p>ユーザーはいません</p>
<% end %>

app/views/users/index.html.erb
<div class="container px-5 px-sm-0">
  <div class="row">
    <div class="col-md-3">
      <%= render 'info', user: @user %>
      <%= render 'books/form', book: @book %>
    </div>

    <div class="col-md-8 offset-md-1">
      <h2>Users</h2>
      <table class="table">
        <thead>
          <tr>
            <th>image</th>
            <th>name</th>
            <th colspan="4"></th>
          </tr>
        </thead>
        <tbody>
          <% @users.each do |user| %>
            <tr>
              <td><%= image_tag user.get_profile_image(80, 80) %></td>
              <td><%= user.name %></td>
              <td>フォロー数: <%= user.following.count %></td>
              <td>フォロワー数: <%= user.followers.count %></td>
              <td>
                <div class="row" id="follow_buttons_<%= user.id %>">
                  <%= render "relationships/relationship", user: user %>
                </div>
              </td>
              <td><%= link_to 'Show', user_path(user) %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/users/search.js.erb
$('#search_result').html("<%= j(render "users/search", search_book: @search_book) %>");

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<div class="container px-5 px-sm-0">
  <div class="row">
    <div class="col-md-3">
      <%= render 'info', user: @user %>
      <%= render 'books/form', book: @book %>
    </div>
    <%= render 'books/list', books: @books %>

    <h3 class="mt-3">投稿数の前日比・前週比</h3>
    <table class="table">
      <tr>
        <th>今日の投稿数</th>
        <th>前日の投稿数</th>
        <th>前日比</th>
      </tr>
      <tr>
        <td><%= @today.count %></td>
        <td><%= @yesterday.count %></td>
        <td>
          <% if @yesterday.count == 0 %>
            前日の投稿はありません
          <% else %>
            <% @the_day_before =   @today.count / @yesterday.count.to_f  %>
            <%= (@the_day_before * 100).round %>%
          <% end %>
       </td>
      </tr>
    </table>

    <table class="table">
      <tr>
        <th>今週の投稿数</th>
        <th>前週の投稿数</th>
        <th>前週比</th>
      </tr>
      <tr>
        <td><%= @this_week.count %></td>
        <td><%= @last_week.count %></td>
        <td>
          <% if @last_week.count == 0 %>
            前日の投稿はありません
          <% else %>
            <% @the_previous_week =   @this_week.count / @last_week.count.to_f  %>
            <%= (@the_previous_week * 100).round %>%
          <% end %>
       </td>
      </tr>
    </table>

    <h3 class="mt-3">7日間分の投稿数</h3>
    <table class="table">
      <tr>
        <th>6日前</th>
        <th>5日前</th>
        <th>4日前</th>
        <th>3日前</th>
        <th>2日前</th>
        <th>1日前</th>
        <th>今日</th>
      </tr>
      <tr>
        <td><%= @books.created_6days.count %></td>
        <td><%= @books.created_5days.count %></td>
        <td><%= @books.created_4days.count %></td>
        <td><%= @books.created_3days.count %></td>
        <td><%= @books.created_2days.count %></td>
        <td><%= @yesterday.count %></td>
        <td><%= @today.count %></td>
      </tr>
    </table>

    <canvas id="myLineChart"></canvas>
    <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
    <script>
      $(document).on('turbolinks:load', function() {
        var ctx = document.getElementById("myLineChart");
        var myLineChart = new Chart(ctx, {
          type: 'line',
          data: {
            labels: ['6日前', '5日前', '4日前', '3日前', '2日前', '1日前', '今日'],
            datasets: [
              {
                label: '投稿した本の数',
                data: [
                  <%= @books.created_6days.count %>,
                  <%= @books.created_5days.count %>,
                  <%= @books.created_4days.count %>,
                  <%= @books.created_3days.count %>,
                  <%= @books.created_2days.count %>,
                  <%= @books.created_yesterday.count %>,
                  <%= @books.created_today.count %>
                ],
                borderColor: "rgba(0,0,255,1)",
                backgroundColor: "rgba(0,0,0,0)",
                tension: 0.4
              }
            ],
          },
          options: {
            title: {
              display: true,
              text: '7日間の投稿数の比較'
            },
            responsive: true,
            scales: {
              y:{
                suggestedMin: 0,
                suggestedMax: 10
              },
              x:{
                stacked: true
              },
            },
          }
        });
      });
    </script>
  </div>

  <div class="row">
    <%= form_with url: user_search_path(@user), local: false, method: :get do |f| %>
      <%= f.date_field :created_at %>
      <%= f.submit "検索", class: "btn btn-primary" %>
    <% end %>
  </div>

  <div class="row" id="search_result">
    <% if @search_book.present? %>
      <% render 'search', search_book: @search_book %>
    <% end %>
  </div>
</div>