config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "homes#top"

  resources :books, only: [:create, :index, :show, :edit, :update, :destroy] do
    resource :favorites, only: [:create, :destroy]
    resources :book_comments, only: [:create, :destroy]
  end

  resources :users, only: [:index, :create, :show, :edit, :update] do
    resource :relationships, only: [:create, :destroy]
    get "search" => "users#search"
    member do
      get :following, :followers
    end
  end

  get "search" => "searches#search"
  get "home/about"=> "homes#about", as: "about"

  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#guest_sign_in'
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/book.rb
class Book < ApplicationRecord

  has_many :book_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :favorited_users, through: :favorites, source: :user
  belongs_to :user

  validates :title, presence: true
  validates :body, presence: true, length: { maximum: 200 }

  scope :created_today, -> { where(created_at: Time.zone.now.all_day) }
  scope :created_yesterday, -> { where(created_at: 1.day.ago.all_day) }
  scope :created_2days, -> { where(created_at: 2.days.ago.all_day) }
  scope :created_3days, -> { where(created_at: 3.days.ago.all_day) }
  scope :created_4days, -> { where(created_at: 4.days.ago.all_day) }
  scope :created_5days, -> { where(created_at: 5.days.ago.all_day) }
  scope :created_6days, -> { where(created_at: 6.days.ago.all_day) }

  scope :created_this_week, -> { where(created_at: 6.day.ago.beginning_of_day..Time.zone.now.end_of_day) }
  scope :created_last_week, -> { where(created_at: 2.week.ago.beginning_of_day..1.week.ago.end_of_day) }

  def favorited_by?(user)
    favorites.exists?(user_id: user.id)
  end

  def self.looks(search, word)
    if search == "perfect_match"
      @book = Book.where("title LIKE?","#{word}")
    elsif search == "forward_match"
      @book = Book.where("title LIKE?","#{word}%")
    elsif search == "backward_match"
      @book = Book.where("title LIKE?","%#{word}")
    elsif search == "partial_match"
      @book = Book.where("title LIKE?","%#{word}%")
    else
      @book = Book.all
    end
  end

end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :is_matching_login_user, only: [:edit, :update]

  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
      redirect_to book_path(@book.id), notice: "You have created book successfully."
    else
      @books = Book.all
      render action: :index
    end
  end

  def index
    to  = Time.current.at_end_of_day
    from  = (to - 6.day).at_beginning_of_day
    @books = Book.includes(:favorited_users).
      sort {|a,b|
        b.favorited_users.includes(:favorites).where(created_at: from...to).size <=>
        a.favorited_users.includes(:favorites).where(created_at: from...to).size
      }
    @book = Book.new
  end

  def show
    @book_id = Book.find(params[:id])
    @book = Book.new
    @user = @book_id.user
    @book_comment = BookComment.new

    current_user.view_counts.create(book_id: @book_id.id)
  end

  def edit
    @book = Book.find(params[:id])
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      redirect_to book_path(@book.id), notice: "You have updated book successfully."
    else
      render action: :edit
    end
  end

  def destroy
    book = Book.find(params[:id])
    book.destroy
    redirect_to '/books'
  end

  private

  def book_params
    params.require(:book).permit(:title, :body)
  end

  def is_matching_login_user
    user = Book.find(params[:id]).user
    unless user.id == current_user.id
      redirect_to books_path
    end
  end

end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/_comment.html.erb
<table class="table">
  <tbody>
    <% book.book_comments.each do |book_comment| %>
      <tr>
        <td>
          <%= image_tag book_comment.user.get_profile_image(100,100) %>
        </td>
        <td>
          <%= book_comment.user.name %>
        </td>
        <td>
          <%= book_comment.created_at.strftime('%Y/%m/%d') %>
        </td>
        <td>
          <%= book_comment.comment %>
        </td>
          <% if book_comment.user == current_user %>
           <td>
             <%= link_to "Destroy", book_book_comment_path(book_comment.book, book_comment), method: :delete, remote: true %>
            </td>
          <% end %>
        </tr>
      <% end %>
  </tbody>
</table>

app/views/books/_comments_count.html.erb
コメント数: <%= book.book_comments.count %>

app/views/books/_form.html.erb
<h2 class="mt-3">New book</h2>
<%= form_with model: book, url: '/books', method: :post do |f| %>
    <div class="form-group">
        <label for="book_title">Title</label>
        <%= f.text_field :title, class: 'form-control' %>
    </div>
     <div class="form-group">
         <label for="book_opinion">Opinion</label>
         <%= f.text_area :body, class: 'form-control' %>
     </div>
    <div class="form-group">
        <%= f.submit 'Create Book', class: 'btn btn-success' %>
    </div>
<% end %>

app/views/books/_list.html.erb
<div class="col-md-8 offset-md-1">
  <h2>Books</h2>
  <table class="table table-hover table-inverse">
    <thead>
      <tr>
        <th></th>
        <th>Title</th>
        <th>Opinion</th>
        <th colspan="3"></th>
      </tr>
    </thead>
    <tbody>
      <% @books.each do |book| %>
      <tr>
        <td>
          <%= link_to user_path(book.user.id) do %>
            <%= image_tag book.user.get_profile_image(80,80) %>
          <% end %>
        </td>
        <td>
          <%= link_to book_path(book.id) do %>
          <%= book.title %>
          <% end %>
        </td>
        <td><%= book.body %></td>
        <td id="favorite_buttons_<%= book.id %>">
          <%= render "favorites/favorite", book: book %>
        </td>
        <td>
          コメント数: <%= book.book_comments.count %>
        </td>
        <td>閲覧数: <%= book.view_counts.count %></td>
      </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/books/edit.html.erb
<% if flash[:notice] %>
  <p id="notice">
     <%= flash[:notice] %>
  </p>
<% end %>

<div class="container">
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
		  <h1>Editing Book</h1>
	    <% if @book.errors.any? %>
        <div id="error_explanation">
          <h2> <%= @book.errors.count %>errors prohibited this book from being saved:</h2>
          <ul>
            <% @book.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
          </ul>
        </div>
      <% end %>
		  <%= form_with model: @book, url: book_path(@book.id), method: :patch do |f| %>
		    <div class="form-group">
		      <label for="book_title">Title</label>
		      <%= f.text_field :title, class: 'form-control' %>
        </div>

        <div class="form-group">
          <label for="book_opinion">Opinion</label>
          <%= f.text_area :body, class: 'form-control' %>
        </div>

        <div class="form-group">
          <%= f.submit 'Update Book', class: 'btn btn-success' %>
        </div>
        <%= link_to "Show", book_path(@book.id) %> | <%= link_to "Back", books_path %>
      <% end %>

		</div>
  </div>
</div>

app/views/books/index.html.erb
<% if flash[:notice] %>
  <p id="notice">
    <%= flash[:notice] %>
   </p>
<% end %>

<div class="container px-5 px-sm-0">
  <% if @book.errors.any? %>
    <div id="error_explanation">
      <h2> <%= @book.errors.count %>errors prohibited this book from being saved:</h2>
      <ul>
        <% @book.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="row">
    <div class="col-md-3">
     <%= render 'users/info', user: current_user %>
     <%= render 'form', book: @book %>
    </div>
    <%= render 'list', books: @books %>
  </div>
</div>

app/views/books/replace_comment.js.erb
$('#comments_count').html("<%= j(render "books/comments_count", book: @book_id) %>");
$('#comments').html("<%= j(render "books/comment", book: @book_id) %>");
$("textarea").val('')

app/views/books/show.html.erb
<% if flash[:notice] %>
  <p id="notice">
     <%= flash[:notice] %>
  </p>
<% end %>

<div class="container px-5 px-sm-0">
  <div class="row">
    <div class="col-md-3">
      <%= render 'users/info', user: @user %>
      <%= render 'form', book: @book %>
    </div>

    <div class="col-md-8 offset-md-1">
      <h2>Book detail</h2>
      <table class="table">
        <tbody>
          <tr>
            <td>
              <%= link_to user_path(@user.id) do %>
                <%= image_tag @book_id.user.get_profile_image(80,80) %>
                <br> <%= @user.name %>
              <% end %>
            </td>
            <td>
              <%= link_to book_path(@book_id) do %>
                <%= @book_id.title %>
              <% end %>
            </td>
            <td><%= @book_id.body %></td>
            <td id="favorite_buttons_<%= @book_id.id %>">
              <%= render "favorites/favorite", book: @book_id %>
            </td>
            <td>
              <div id="comments_count">
                <%= render "comments_count", book: @book_id %>
              </div>
            </td>
            <td>閲覧数: <%= @book_id.view_counts.count %></td>

            <% if @book_id.user == current_user %>
              <td>
                <%= link_to edit_book_path(@book_id), class: 'btn btn-sm btn-success' do %>
                  Edit
                <% end %>
              </td>
              <td>
                <%= link_to book_path(@book_id), method: :delete, class: 'btn btn-sm btn-danger' do %>
                  Destroy
                <% end %>
              </td>
            <% end %>
          </tr>
        </tbody>
      </table>

      <div id="comments">
        <%= render "comment", book: @book_id %>
      </div>

      <%= form_with(model: [@book_id, @book_comment], local: false) do |f| %>
        <div class="form-group">
          <%= f.text_area :comment, rows: '5', class: 'form-control' %>
        </div>
        <div class="form-group">
          <%= f.submit "送信" %>
        </div>
      <% end %>

    </div>
  </div>
</div>