config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "homes#top"

  resources :books, only: [:create, :index, :show, :edit, :update, :destroy] do
    resource :favorites, only: [:create, :destroy]
    resources :book_comments, only: [:create, :destroy]
  end

  resources :users, only: [:index, :create, :show, :edit, :update] do
    resource :relationships, only: [:create, :destroy]
    get "search" => "users#search"
    member do
      get :following, :followers
    end
  end

  get "search" => "searches#search"
  get "home/about"=> "homes#about", as: "about"

  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#guest_sign_in'
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController
  before_action :authenticate_user!

  def search
    @range = params[:range]
    @word = params[:word]

    if @range == "User"
      @users = User.looks(params[:search], params[:word])
    else
      @books = Book.looks(params[:search], params[:word])
    end
  end
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/views/searches/search.html.erb
<% if @range == "User" %>
  <h2>Users search for &quot;<%= @word %>&quot;</h2>

  <table class="table table-hover table-inverse">
    <thead>
      <tr>
        <th></th>
        <th>Image</th>
        <th>Name</th>
        <th colspan="3"></th>
      </tr>
    </thead>
    <tbody>
      <% @users.each do |user| %>
        <tr>
          <td>
            <%= link_to user_path(user.id) do %>
              <%= image_tag user.get_profile_image(80,80) %>
            <% end %>
          </td>
          <td>
            <%= link_to user_path(user.id) do %>
              <%= user.name %>
            <% end %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% else %>
  <h2>Books search for &quot;<%= @word %>&quot;</h2>

  <table class="table table-hover table-inverse">
    <thead>
      <tr>
        <th></th>
        <th>Title</th>
        <th>Opinion</th>
        <th colspan="3"></th>
      </tr>
    </thead>
    <tbody>
      <% @books.each do |book| %>
        <tr>
          <td>
            <%= link_to user_path(book.user.id) do %>
              <%= image_tag book.user.get_profile_image(80,80) %>
            <% end %>
          </td>
          <td>
            <%= link_to book_path(book.id) do %>
              <%= book.title %>
            <% end %>
          </td>
          <td><%= book.body %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% end %>