config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "homes#top"

  resources :books, only: [:create, :index, :show, :edit, :update, :destroy] do
    resource :favorites, only: [:create, :destroy]
    resources :book_comments, only: [:create, :destroy]
  end

  resources :users, only: [:index, :create, :show, :edit, :update] do
    resource :relationships, only: [:create, :destroy]
    get "search" => "users#search"
    member do
      get :following, :followers
    end
  end

  get "search" => "searches#search"
  get "home/about"=> "homes#about", as: "about"

  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#guest_sign_in'
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/layouts/_errors.html.erb
<% if obj.errors.any? %>
  <div id="error_explanation">
    <h6><%= pluralize(obj.errors.count, "error") %> prohibited this obj from being saved:</h3>
    <ul>
      <% obj.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_notifications.html.erb
<% flash.each do |key, value| %>
  <%= content_tag(:div, value, class: "#{key}" ) %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container">
          <a class="navbar-brand" href="/"><span>Bookers</span></a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="navbar-collapse collapse" id="navbarNavDropdown" style="">
            <ul class="navbar-nav ml-auto">
              <% if user_signed_in? %>
                <li>
                  <%= link_to user_path(current_user), class: 'nav-link text-light' do %>
                    <i class="fas fa-home"></i> Home
                  <% end %>
                </li>
                <li>
                  <%= link_to users_path, class: 'nav-link text-light' do %>
                    <i class="fas fa-users"></i> Users
                  <% end %>
                </li>
                <li>
                  <%= link_to books_path, class: 'nav-link text-light' do %>
                    <i class="fas fa-book-open"></i> Books
                  <% end %>
                </li>
                <li>
                  <%= link_to destroy_user_session_path, method: :delete, class: 'nav-link text-light' do %>
                  <i class="fas fa-sign-out-alt"></i> Logout
                  <% end %>
                </li>
              <% else %>
                <li>
                  <%= link_to root_path, class: 'nav-link text-light' do %>
                    <i class="fas fa-home"></i> Home
                  <% end %>
                </li>
                <li>
                  <%= link_to about_path, class: 'nav-link text-light' do %>
                  <i class="fas fa-link"></i> About
                  <% end %>
                </li>
                <li>
                  <%= link_to new_user_registration_path, class: 'nav-link text-light' do %>
                  <i class="fas fa-user-plus"></i> sign up
                  <% end %>
                </li>
                <li>
                  <%= link_to new_user_session_path, class: 'nav-link text-light' do %>
                  <i class="fas fa-sign-in-alt"></i> Login
                  <% end %>
                </li>
              <% end %>
            </ul>
          </div>
        </div>
      </nav>
      <% if user_signed_in? %>
        <div class="container mt-1 mb-3">
      	  <div class="row">
            <div class="mx-auto">
              <%= form_with url: search_path, local: true, method: :get do |f| %>
                <%= f.text_field :word %>
                <%= f.select :range, options_for_select([['User'], ['Book']]) %>
                <%= f.select :search, options_for_select([["完全一致","perfect_match"], ["前方一致","forward_match"],  ["後方一致","backward_match"], ["部分一致","partial_match"]]) %>
                <%= f.submit "検索", class: "btn btn-primary" %>
              <% end %>
            </div>
          </div>
        </div>
      <% end %>
    </header>
    <main>
      <%= yield %>
    </main>
    <footer>
      <div class="container mt-5">
    	  <div class="row">
    	    <div class="mx-auto">
    	  	  <p>CopyRight Infratop.inc</p>
    	  	</div>
        </div>
      </div>
    </footer>

  </body>
</html>